language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
script: "pyb verify analyze"
after_success:
  - coveralls --verbose